# Generated by Django 2.1.3 on 2018-11-30 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('BOY', 'Boy'), ('GIRL', 'Girl')], default=None, max_length=5)),
                ('picture', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('date_of_birth', models.DateField()),
                ('size_system', models.CharField(choices=[('EU', 'EU'), ('UK', 'UK'), ('US', 'US')], default='EU', max_length=5)),
                ('corrected_sizes', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, '32'), (1, '38'), (2, '44'), (3, '50'), (4, '56'), (5, '62'), (6, '68'), (7, '74'), (8, '80'), (9, '86'), (10, '92'), (11, '98'), (12, '104'), (13, '110'), (14, '116'), (15, '122'), (16, '128'), (17, '134'), (18, '140'), (19, '146'), (20, '152')], default=None, max_length=52, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullTermChild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Child')),
            ],
            bases=('home.child',),
        ),
        migrations.CreateModel(
            name='NotBornChild',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Child')),
            ],
            bases=('home.child',),
        ),
        migrations.CreateModel(
            name='Preemie',
            fields=[
                ('child_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.Child')),
            ],
            bases=('home.child',),
        ),
        migrations.AddField(
            model_name='child',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
