# Generated by Django 2.1.3 on 2018-12-11 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, choices=[('BOY', 'Boy'), ('GIRL', 'Girl')], default=None, max_length=5, null=True)),
                ('picture', models.ImageField(blank=True, default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('size_system', models.CharField(choices=[('EU', 'EU'), ('UK', 'UK'), ('US', 'US')], default='EU', max_length=5)),
                ('child_status', models.CharField(choices=[('F', 'Full term'), ('P', 'Preemie'), ('Not born yet', 'Not born yet')], default='F', max_length=15)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
